### ISSUE TITLE
How did you play around with ZSI?

### ISSUE THREAD

**Issue by algoteam5** [noobying/mmdetection_2.14.0_Zero-Shot_Instance_Segmenation#1]
Hello, I am following ZSI work too. However, It is quite challenging for me to edit the original code and play around with it. I saw you did some changes in the background-awareness class. How are you able to do that? It is difficult for me to understand the original work by reading code.

**Comment by noobying** [comment]
I don't understand what you mean. Please specify which code line confuse you. BTW, I just start to update the origin official project to mmdet2.14.0, there may be some errors. I will finish this repo ASAP.

**Comment by algoteam5** [comment]
I am getting overwhelmed by this work. There are so many things. Could you please specify the flow of the work?.
For example, First the model run detection by running `zero_shot_two_stage`, and then `convfc_bbox_semantic_head` is used to create bounding box etc...

**Comment by noobying** [comment]
This work is done in the `mmdetection`(*best detection* framework in the world😊). The workflow is a little complexity due to its High cohesion and low coupling. I will sort out the whole process when finishing this work ASAP.

**Comment by algoteam5** [comment]
Thank you, in the meantime, could you share some links where you read about the work flow of the framework?

**Comment by noobying** [comment]
> Thank you, in the meantime, could you share some links where you read about the work flow of the framework?

I get the chinese version blog by mmdetection. [here](https://zhuanlan.zhihu.com/p/346198300)

**Comment by algoteam5** [comment]
Wow, Very informative post. Thank you!!

**Comment by noobying** [comment]
You are welcome! If you get any problems, feel free to post a issue here. Good luck!
